### ISSUE TITLE
xorm supporting

### ISSUE THREAD

**Issue by rush24** [knocknote/octillery#14]
> Octillery replace import statement of database/sql to go.knocknote.io/octillery/database/sql. Therefore, OR Mapping library call Octillery's interface. and it can capture all queries.  

We don't import the `database/sql` in project directly but in xorm, so should we replace the xorm pkg? if so how to solve the dependency problem with go mod?

**Comment by goccy** [comment]
Hi, thanks for using this library.
`Octillery` can replace import statement of `github.com/go-sql-driver/mysql` .

For example, if you use `xorm` with `go-sql-driver/mysql` , the following.

```go
package main
 
import (
    "github.com/go-xorm/xorm"
    _ "github.com/go-sql-driver/mysql"
)
 
func main() {
    engine, err := xorm.NewEngine("mysql", "root:pass@/golang")
    if err != nil {
        panic(err)
    }
}
```

1. `octillery transpose --dry-run /go/pkg/mod` ( if you use `Go Modules` )
2. `octillery install --mysql` ( install `mysql` driver for octillery )

By these flow, `Octillery` can capture all queries. ( `xorm` => `go-sql-driver/mysql` => `octillery/database/sql` )

Please try to do the above approeach.

Thanks.

**Comment by rush24** [comment]
`--dry-run` only show the diff, my problem is it only happends in local if i just replacing all the statements under `$GOPATH/pkg/mod` ，but how to resolve the remote version control?

**Comment by goccy** [comment]
Yes, `--dry-run` option shows only diff.  
Actually, you need to do `octillery transpose $GOPATH/pkg/mod` .

I still don't understand your situation. 
If you want to commit diff of under `$GOPATH/pkg/mod`, I know could resolve it what do symlink or mount volume ( for Docker ) from `$GOPATH/pkg/mod` to `pkg/mod` on workspace or `go mod vendor`.

**Comment by rush24** [comment]
My point is that It's not a good practice to modify dependent pkg, which makes it likes folk.
Normally we do not commit the dependent pkg, we judt commiting the specific version of the pkg and go build or test in remote CI&CD.

**Comment by goccy** [comment]
I also suggest the following.

- go.mod

```
replace github.com/go-sql-driver/mysql => ./vendor/github.com/go-sql-driver/mysql
```

.. and only commit `vendor/github.com/go-sql-driver` .

If you do not want commit any dependencies, always must do `octillery transpose` before testing or building .

Thanks
